import { readable, writable } from 'svelte/store';

export const game = {
  letters: readable([
    "B",
    "C",
    "D",
    "F",
    "G",
    "H",
    "J",
    "K",
    "L",
    "M",
    "N",
    "P",
    "R",
    "S",
    "T",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ]),
  targets: readable([
    "B",
    "C",
    "D",
    "F",
    "G",
    "H",
    "J",
    "K",
    "L",
    "M",
    "N",
    "P",
    "R",
    "S",
    "T",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ]),
  distractors: readable([
    "rgb(0,0,255)",      // blue
    "rgb(200,200,0)",    // yellow
    "rgb(200,0,200)",    // magenta
    "rgb(0,200,200)",    // cyan
    "rgb(200,200,200)",  // light grey
    "rgb(50,50,50)",     // dark grey
  ]),
  totalTrials: readable(96),
  correct: writable(0),
  incorrect: writable(0),
  currentLetter: writable(' '),
  receivedLetter: writable(' '),
  showLetter: writable(true),
  targetLetter: writable("X"),
  targetIndex: writable(14),
  isTarget: writable(false),
  boxIndex: writable(null),
  isBoxRed: writable(false),
  isBoxGreen: writable(false),
  textColor: writable(null),
  plays: writable(0),
  currentTrial: writable(92),
  started: writable(false),
  guessed: writable(true),
  reactionTime: writable(0),
  startTime: writable(null),
  AB: writable(false),
  CC: writable(false),
  SiB: writable(false),
  guesses: writable([]),
  surpriseTrials: writable([]),
  displayFace: writable(false),
  targetLetters: writable([]),
  buttonText: writable("Start"),
  clicked: writable(false),
  everyTarget: writable([]),
  everyGuess: writable([]),
  everyAccuracy: writable([]),
  everyReactionTime: writable([]),
  trialType: writable(null),
  isPractice: writable(false),
};

